/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

export const TUI_COPY_RESOURCES = {
  copy: {
    en: {
      copiedLast:
        'Sent the last reply to the terminal via OSC 52 · {count, plural, one {# char} other {# chars}} — it reaches the clipboard only if your terminal (and tmux, if used) allows OSC 52 writes.',
      copiedAll:
        'Sent the conversation to the terminal via OSC 52 · {count, plural, one {# char} other {# chars}} — it reaches the clipboard only if your terminal (and tmux, if used) allows OSC 52 writes.',
      tooLarge:
        'Too large to copy over OSC 52 · {bytes} bytes exceeds the {limit}-byte limit; a larger payload is silently dropped by the terminal.',
      nothingToCopy: 'Nothing to copy yet.',
      usage: 'Usage: /copy [all]',
      roleUser: 'You:',
      roleAssistant: 'Maka:',
      roleGoalContinuation: 'Goal continuation (autonomous):',
      roleLegacyAutomation: 'Legacy automation (history only):',
    },
    'zh-CN': {
      copiedLast:
        '已将最后一条回复发送到终端 · {count} 个字符——仅当终端（以及 tmux，如使用）允许写入剪贴板时才会真正复制。',
      copiedAll:
        '已将整段对话发送到终端 · {count} 个字符——仅当终端（以及 tmux，如使用）允许写入剪贴板时才会真正复制。',
      tooLarge:
        '内容过大，无法复制 · {bytes} 字节超过 {limit} 字节上限；更大的内容会被终端静默丢弃。',
      nothingToCopy: '暂无可复制的内容。',
      usage: '用法：/copy [all]',
      roleUser: '你：',
      roleAssistant: 'Maka：',
      roleGoalContinuation: '目标续跑（自主）：',
      roleLegacyAutomation: '旧版自动化（仅历史）：',
    },
    'zh-TW': {
      copiedLast:
        '已將最後一則回覆傳送至終端機 · {count} 個字元——僅當終端機（以及 tmux，如有使用）允許寫入剪貼簿時才會真正複製。',
      copiedAll:
        '已將整段對話傳送至終端機 · {count} 個字元——僅當終端機（以及 tmux，如有使用）允許寫入剪貼簿時才會真正複製。',
      tooLarge:
        '內容過大，無法複製 · {bytes} 位元組超過 {limit} 位元組上限；更大的內容會被終端機直接捨棄。',
      nothingToCopy: '目前沒有可複製的內容。',
      usage: '用法：/copy [all]',
      roleUser: '你：',
      roleAssistant: 'Maka：',
      roleGoalContinuation: 'Goal 繼續執行（自主）：',
      roleLegacyAutomation: '舊版自動化（僅歷史）：',
    },
  },
  'mcp-status': {
    en: {
      title: 'MCP SERVERS',
      footer: {
        back: 'Esc back',
        readOnly: '↑/↓ scroll · q/Esc close',
        manage:
          'a Add · Enter Edit · Space Enable/disable · t Test · r Reconnect · d Remove · Esc Close',
        managePublication:
          'a Add · Enter Edit · Space Enable/disable · t Test · r Reconnect · d Remove · p Set provider credential · x Remove credential · Esc Close',
      },
      unavailableTitle: 'This TUI is not connected to a local MCP control plane.',
      unavailableDetail:
        'Client MCP tool association for remote Runtime Hosts is planned for a later release.',
      loading: 'Loading mcp.json and discovering tools…',
      loadError:
        'MCP configuration could not be loaded; no tools were published to the Runtime Host.',
      noServers: 'No MCP servers are configured. Press a to add one.',
      publication: {
        waiting: 'waiting to publish',
        host_unavailable: 'Runtime Host reconnecting',
        credential_required: 'provider credential required',
        credential_rejected: 'provider credential rejected',
        provider_conflict: 'provider active in another TUI',
        target_mismatch: 'provider target mismatch',
        publishing: 'publishing',
        published: 'published',
        not_published: 'not published',
        error: 'publication failed',
      },
      serverState: {
        disabled: 'disabled',
        disconnected: 'disconnected',
        connecting: 'connecting',
        connected: 'connected',
        'needs-auth': 'needs-auth',
        error: 'error',
      },
      configuredOnly: 'configured only',
      configPending: 'config pending',
      toolCount: '{count, plural, one {# tool} other {# tools}}',
      connectionFailed: 'MCP server connection failed',
      editor: {
        addTitle: 'Add MCP server',
        transportTitle: 'Transport',
        protocolTitle: 'Protocol preference',
        confirmAddTitle: 'Add this MCP server?',
        confirmImportTitle: 'Import MCP servers?',
        confirmRemoveTitle: 'Remove {serverId}?',
        confirmRemoveCredentialTitle: 'Remove the remote provider credential?',
        confirmRemoveCredentialDetail:
          'This stops publishing MCP tools to the selected Runtime Host.',
        confirmHint: 'y Confirm · Esc cancel',
        synchronizing: 'Configuration is synchronizing…',
        outOfSync: 'Durable configuration and MCP Manager are out of sync.',
        action: {
          test: 'Testing MCP server…',
          reconnect: 'Reconnecting MCP server…',
          apply: 'Applying MCP configuration…',
        },
        inputLabels: {
          server_id: 'Server ID',
          command: 'Command',
          args: 'Arguments',
          url: 'Streamable HTTP URL',
          cwd: 'Working directory',
          env: 'Environment',
          headers: 'Request headers',
          edit: 'Edit server JSON',
          import: 'Paste MCP JSON',
          publication_credential: 'Provider credential',
        },
        hints: {
          args: 'JSON string array, optional',
          map: 'JSON string map, optional',
          optional: 'optional',
          submit: 'Enter submit · Esc back',
          credential:
            'Stored only in the local credential store; never written to profiles, arguments, or chat · Enter submit · Esc back',
        },
        results: {
          exists: 'That server ID already exists.',
          stale_config: 'MCP configuration changed; retry the action.',
          stale_edit: 'This server changed; reopen it before editing.',
          stale_import: 'An imported entry changed; preview the import again.',
          missing: 'That server no longer exists.',
          closed: 'The MCP controller is closed.',
          'invalid-config': 'The server configuration is invalid.',
          'credential-cleanup-failed':
            'Stored credentials could not be removed; the configuration was not changed.',
          'publication-credential-failed':
            'The provider credential could not be stored or applied.',
          'persist-failed': 'The configuration could not be saved.',
          'manager-failed': 'The MCP connection action failed.',
          turn_active: 'MCP cannot be changed while a turn or another control action is running.',
          invalid: 'Check the value and try again.',
          published: 'Configuration saved and tools refreshed.',
          pending_host: 'Configuration saved; publication is waiting for Runtime Host.',
          sync_failed: 'Configuration saved, but the MCP manager is out of sync.',
          publication_failed: 'Configuration saved, but capability publication failed.',
          test_ok: 'Connection test passed.',
          test_failed: 'Connection test failed.',
          test_publication_failed: 'Connection test passed, but capability publication failed.',
          test_pending_host: 'Connection test passed; publication is waiting for Runtime Host.',
        },
      },
    },
    'zh-CN': {
      title: 'MCP 服务器',
      footer: {
        back: 'Esc 返回',
        readOnly: '↑/↓ 滚动 · q/Esc 关闭',
        manage: 'a 添加 · Enter 编辑 · Space 启用/停用 · t 测试 · r 重连 · d 删除 · Esc 关闭',
        managePublication:
          'a 添加 · Enter 编辑 · Space 启用/停用 · t 测试 · r 重连 · d 删除 · p 设置 Provider 凭据 · x 删除凭据 · Esc 关闭',
      },
      unavailableTitle: '当前 TUI 未连接本地 MCP 控制面。',
      unavailableDetail: '远程 Runtime Host 的客户端 MCP 工具关联将在后续版本提供。',
      loading: '正在读取 mcp.json 并发现工具…',
      loadError: '无法读取或应用 MCP 配置；没有向 Runtime Host 发布工具。',
      noServers: '尚未配置 MCP 服务器。按 a 添加。',
      publication: {
        waiting: '等待发布',
        host_unavailable: 'Runtime Host 重连中',
        credential_required: '需要 Provider 凭据',
        credential_rejected: 'Provider 凭据已被拒绝',
        provider_conflict: 'Provider 已在另一个 TUI 中运行',
        target_mismatch: 'Provider 目标不匹配',
        publishing: '正在发布',
        published: '已发布',
        not_published: '未发布',
        error: '发布失败',
      },
      serverState: {
        disabled: '已停用',
        disconnected: '未连接',
        connecting: '连接中',
        connected: '已连接',
        'needs-auth': '需要登录',
        error: '错误',
      },
      configuredOnly: '仅已配置',
      configPending: '配置待同步',
      toolCount: '{count} 个工具',
      connectionFailed: 'MCP 服务器连接失败',
      editor: {
        addTitle: '添加 MCP 服务器',
        transportTitle: '传输方式',
        protocolTitle: '协议偏好',
        confirmAddTitle: '添加该 MCP 服务器？',
        confirmImportTitle: '导入 MCP 服务器？',
        confirmRemoveTitle: '删除 {serverId}？',
        confirmRemoveCredentialTitle: '删除远程 Provider 凭据？',
        confirmRemoveCredentialDetail: '这会停止向所选 Runtime Host 发布 MCP 工具。',
        confirmHint: 'y 确认 · Esc 取消',
        synchronizing: '配置同步中…',
        outOfSync: '持久化配置与 MCP Manager 尚未同步。',
        action: {
          test: '正在测试 MCP 服务器…',
          reconnect: '正在重连 MCP 服务器…',
          apply: '正在应用 MCP 配置…',
        },
        inputLabels: {
          server_id: '服务器 ID',
          command: '命令',
          args: '参数',
          url: 'Streamable HTTP URL',
          cwd: '工作目录',
          env: '环境变量',
          headers: '请求头',
          edit: '编辑服务器 JSON',
          import: '粘贴 MCP JSON',
          publication_credential: 'Provider 凭据',
        },
        hints: {
          args: 'JSON string array, 可留空',
          map: 'JSON string map, 可留空',
          optional: '可留空',
          submit: 'Enter 提交 · Esc 返回',
          credential: '仅保存到本机凭据存储；不会写入 profile、参数或对话 · Enter 提交 · Esc 返回',
        },
        results: {
          exists: '该服务器 ID 已存在。',
          stale_config: 'MCP 配置已变化，请重试。',
          stale_edit: '该服务器已变化，请重新打开后编辑。',
          stale_import: '导入项已变化，请重新预览。',
          missing: '该服务器已不存在。',
          closed: 'MCP 控制器已关闭。',
          'invalid-config': '服务器配置无效。',
          'credential-cleanup-failed': '无法删除旧凭据，配置未修改。',
          'publication-credential-failed': '无法保存或应用 Provider 凭据。',
          'persist-failed': '无法保存配置。',
          'manager-failed': 'MCP 连接操作失败。',
          turn_active: 'Turn 或其他控制操作运行期间不能修改 MCP。',
          invalid: '请检查输入后重试。',
          published: '配置已保存，工具已刷新。',
          pending_host: '配置已保存，正等待 Runtime Host 发布。',
          sync_failed: '配置已保存，但 MCP Manager 尚未同步。',
          publication_failed: '配置已保存，但 capability 发布失败。',
          test_ok: '连接测试通过。',
          test_failed: '连接测试失败。',
          test_publication_failed: '连接测试通过，但 capability 发布失败。',
          test_pending_host: '连接测试通过，正等待 Runtime Host 发布。',
        },
      },
    },
    'zh-TW': {
      title: 'MCP 伺服器',
      footer: {
        back: 'Esc 返回',
        readOnly: '↑/↓ 捲動 · q/Esc 關閉',
        manage: 'a 新增 · Enter 編輯 · Space 啟用/停用 · t 測試 · r 重新連線 · d 刪除 · Esc 關閉',
        managePublication:
          'a 新增 · Enter 編輯 · Space 啟用/停用 · t 測試 · r 重新連線 · d 刪除 · p 設定 Provider 認證資料 · x 刪除認證資料 · Esc 關閉',
      },
      unavailableTitle: '目前 TUI 未連線至本機 MCP 控制介面。',
      unavailableDetail: '遠端 Runtime Host 的用戶端 MCP 工具關聯將於後續版本提供。',
      loading: '正在讀取 mcp.json 並探索工具…',
      loadError: '無法讀取或套用 MCP 設定；未向 Runtime Host 發佈任何工具。',
      noServers: '尚未設定 MCP 伺服器。按 a 新增。',
      publication: {
        waiting: '等待發佈',
        host_unavailable: 'Runtime Host 重新連線中',
        credential_required: '需要 Provider 認證資料',
        credential_rejected: 'Provider 認證資料遭拒',
        provider_conflict: 'Provider 已在另一個 TUI 中執行',
        target_mismatch: 'Provider 目標不符',
        publishing: '正在發佈',
        published: '已發佈',
        not_published: '未發佈',
        error: '發佈失敗',
      },
      serverState: {
        disabled: '已停用',
        disconnected: '未連線',
        connecting: '連線中',
        connected: '已連線',
        'needs-auth': '需要登入',
        error: '錯誤',
      },
      configuredOnly: '僅已設定',
      configPending: '設定待同步',
      toolCount: '{count} 個工具',
      connectionFailed: 'MCP 伺服器連線失敗',
      editor: {
        addTitle: '新增 MCP 伺服器',
        transportTitle: '傳輸方式',
        protocolTitle: '通訊協定偏好',
        confirmAddTitle: '新增這個 MCP 伺服器？',
        confirmImportTitle: '匯入 MCP 伺服器？',
        confirmRemoveTitle: '刪除 {serverId}？',
        confirmRemoveCredentialTitle: '移除遠端 Provider 認證資料？',
        confirmRemoveCredentialDetail: '這將停止向所選 Runtime Host 發佈 MCP 工具。',
        confirmHint: 'y 確認 · Esc 取消',
        synchronizing: '設定同步中…',
        outOfSync: '持久化設定與 MCP Manager 尚未同步。',
        action: {
          test: '正在測試 MCP 伺服器…',
          reconnect: '正在重新連線 MCP 伺服器…',
          apply: '正在套用 MCP 設定…',
        },
        inputLabels: {
          server_id: '伺服器 ID',
          command: '命令',
          args: '參數',
          url: 'Streamable HTTP URL',
          cwd: '工作目錄',
          env: '環境變數',
          headers: '請求標頭',
          edit: '編輯伺服器 JSON',
          import: '貼上 MCP JSON',
          publication_credential: 'Provider 認證資料',
        },
        hints: {
          args: 'JSON 字串陣列，可留空',
          map: 'JSON 字串對映，可留空',
          optional: '可留空',
          submit: 'Enter 送出 · Esc 返回',
          credential:
            '僅儲存於本機認證資料存放區；不會寫入設定檔、參數或聊天內容 · Enter 送出 · Esc 返回',
        },
        results: {
          exists: '該伺服器 ID 已存在。',
          stale_config: 'MCP 設定已變更，請重試。',
          stale_edit: '該伺服器已變更，請重新開啟後編輯。',
          stale_import: '匯入項目已變更，請重新預覽。',
          missing: '該伺服器已不存在。',
          closed: 'MCP 控制器已關閉。',
          'invalid-config': '伺服器設定無效。',
          'credential-cleanup-failed': '無法移除已儲存的認證資料；設定未變更。',
          'publication-credential-failed': '無法儲存或套用 Provider 認證資料。',
          'persist-failed': '無法儲存設定。',
          'manager-failed': 'MCP 連線操作失敗。',
          turn_active: 'Turn 或其他控制操作執行期間無法修改 MCP。',
          invalid: '請檢查輸入後重試。',
          published: '設定已儲存，工具已重新整理。',
          pending_host: '設定已儲存，正等待 Runtime Host 發佈。',
          sync_failed: '設定已儲存，但 MCP Manager 尚未同步。',
          publication_failed: '設定已儲存，但 capability 發佈失敗。',
          test_ok: '連線測試通過。',
          test_failed: '連線測試失敗。',
          test_publication_failed: '連線測試通過，但 capability 發佈失敗。',
          test_pending_host: '連線測試通過，正等待 Runtime Host 發佈。',
        },
      },
    },
  },
  'form-interaction': {
    en: {
      requestedBy: 'Requested by {detail}',
      sensitiveWarning: 'Do not enter passwords, API keys, access tokens, or payment details.',
      required: 'required',
      optional: 'optional',
      omitted: 'omitted',
      empty: 'empty',
      invalid: "Value does not meet this field's constraints",
      minimumLength: 'At least {minimum} characters',
      maximumLength: 'At most {maximum} characters',
      lengthRange: '{minimum}–{maximum} characters',
      minimumValue: 'Minimum {minimum}',
      maximumValue: 'Maximum {maximum}',
      valueRange: 'Range {minimum}–{maximum}',
      minimumItems: 'Select at least {minimum}',
      maximumItems: 'Select at most {maximum}',
      itemRange: 'Select {minimum}–{maximum}',
      format: 'Format: {format}',
      reviewHint: '↑↓ field · Enter edit · Space include/omit · s submit · d decline · Esc cancel',
      textHint: 'Type a value · Enter review · Esc review',
      choiceHint: '↑↓ select · Enter review · Esc review',
      multiHint: '↑↓ move · Space toggle · Enter review · Esc review',
      trueValue: 'true',
      falseValue: 'false',
      selectedCount: '{count} selected',
    },
    'zh-CN': {
      requestedBy: '由 {detail} 请求',
      sensitiveWarning: '请勿输入密码、API 密钥、访问令牌或支付信息。',
      required: '必填',
      optional: '选填',
      omitted: '未提供',
      empty: '空',
      invalid: '该值不符合字段约束',
      minimumLength: '至少 {minimum} 个字符',
      maximumLength: '最多 {maximum} 个字符',
      lengthRange: '长度 {minimum}–{maximum} 个字符',
      minimumValue: '最小值 {minimum}',
      maximumValue: '最大值 {maximum}',
      valueRange: '范围 {minimum}–{maximum}',
      minimumItems: '至少选择 {minimum} 项',
      maximumItems: '最多选择 {maximum} 项',
      itemRange: '选择 {minimum}–{maximum} 项',
      format: '格式：{format}',
      reviewHint: '↑↓ 选择字段 · Enter 编辑 · Space 提供/省略 · s 提交 · d 拒绝 · Esc 取消',
      textHint: '输入值 · Enter 返回检查 · Esc 返回检查',
      choiceHint: '↑↓ 选择 · Enter 返回检查 · Esc 返回检查',
      multiHint: '↑↓ 移动 · Space 切换 · Enter 返回检查 · Esc 返回检查',
      trueValue: '是',
      falseValue: '否',
      selectedCount: '已选择 {count} 项',
    },
    'zh-TW': {
      requestedBy: '由 {detail} 請求',
      sensitiveWarning: '請勿輸入密碼、API 金鑰、存取權杖或付款資訊。',
      required: '必填',
      optional: '選填',
      omitted: '未提供',
      empty: '空',
      invalid: '該值不符合欄位約束',
      minimumLength: '至少 {minimum} 個字元',
      maximumLength: '最多 {maximum} 個字元',
      lengthRange: '長度 {minimum}–{maximum} 個字元',
      minimumValue: '最小值 {minimum}',
      maximumValue: '最大值 {maximum}',
      valueRange: '範圍 {minimum}–{maximum}',
      minimumItems: '至少選取 {minimum} 項',
      maximumItems: '最多選取 {maximum} 項',
      itemRange: '選取 {minimum}–{maximum} 項',
      format: '格式：{format}',
      reviewHint: '↑↓ 選取欄位 · Enter 編輯 · Space 提供/省略 · s 提交 · d 拒絕 · Esc 取消',
      textHint: '輸入值 · Enter 返回檢查 · Esc 返回檢查',
      choiceHint: '↑↓ 選取 · Enter 返回檢查 · Esc 返回檢查',
      multiHint: '↑↓ 移動 · Space 切換 · Enter 返回檢查 · Esc 返回檢查',
      trueValue: '是',
      falseValue: '否',
      selectedCount: '已選取 {count} 項',
    },
  },
  pickers: {
    en: {
      modelPickerTitle: 'Select Model',
      modelSwitchCacheWarning:
        '⚠ Switching models may rebuild the prompt cache; the next request may be slower or cost more.',
      modelSearchHint:
        'Search models / providers / connections · ↑↓ select · Enter confirm · Esc cancel',
      searchLabel: 'Search',
      noMatchingModels: 'No matching models',
      selectPickerHint: '↑↓ select · Enter confirm · Esc close',
      providerConfigured: 'configured',
      addAccount: 'add account',
      thinkingLevels: {
        off: 'Off',
        minimal: 'Minimal',
        low: 'Low',
        medium: 'Medium',
        high: 'High',
        xhigh: 'Extra high',
        max: 'Maximum',
      },
      defaultThinkingLevel: 'Default',
      thinkingPickerTitle: 'Select Thinking Level',
      currentMarker: 'current',
      defaultMarker: 'default',
      setupTitle: 'Set Up Provider',
      baseUrlLabel: 'Base URL',
      apiKeyLabel: 'API key',
      connectionNameLabel: 'Name',
      connectionSlugLabel: 'Slug',
      identityHint:
        'Name this connection, or keep the defaults to auto-assign · Enter continues · Esc returns',
      identitySlugInvalid: 'Slug must be 2–64 characters: lowercase letters, digits, and hyphens',
      identityNameTooLong: 'Name must be 256 characters or fewer',
      onboardingUnavailable:
        'Onboarding is unavailable: this environment does not provide a setup surface.',
      onboardingRequestFailed: 'Could not reach the Runtime Host. Try again.',
      onboardingRejections: {
        provider_unsupported: 'This provider does not support API-key onboarding.',
        connection_not_found: 'This connection no longer exists. Reopen /setup and try again.',
        credential_not_configured: 'An API key is required.',
        base_url_not_configured: 'A Base URL is required for this provider.',
        catalog_full: 'The connection catalog is full.',
        model_unavailable: 'A selected model is no longer available. Verify and select again.',
        slug_taken: 'That slug is already taken. Pick another, or clear it to auto-assign.',
        superseded: 'This connection changed. Reopen /setup and try again.',
      },
      onboardingFailures: {
        auth: 'Provider authentication failed. Check the API key and try again.',
        timeout: 'Provider verification timed out. Try again.',
        provider_unavailable: 'The provider is unavailable. Try again later.',
        network: 'A network error interrupted provider verification. Try again.',
        invalid_response: 'The provider returned an invalid response. Try again.',
        unknown: 'Provider verification failed. Try again.',
      },
      accountSavedRefreshFailed:
        'Account saved, but the model list has not refreshed. Restart Maka to reload it.',
      listProvidersFailed: 'Could not read configured connections.',
      noConfigurableProviders: 'No configurable API key providers are available.',
      baseUrlRequired: 'Enter a Base URL',
      baseUrlInvalid: 'Base URL is not a valid URL',
      baseUrlProtocol: 'Base URL must use http or https',
      baseUrlCredentials: 'Base URL cannot include credentials',
      baseUrlQuery: 'Base URL cannot include a query or fragment',
      baseUrlTooLong: 'Base URL cannot exceed 2048 bytes',
      selectModelBeforeSaving: 'Select at least one model before saving',
      reuseBaseUrlHint:
        'Leave blank to reuse the saved Base URL, or enter a replacement · Esc returns to provider selection',
      enterBaseUrlHint: 'Enter the relay Base URL (http/https) · Esc returns to provider selection',
      continueAction: 'Enter to continue',
      providerSearchHint: 'Search providers · ↑↓ select · Enter confirm · Esc cancel',
      noMatchingProviders: 'No matching providers',
      keyHints: {
        reuse: {
          baseUrl:
            'Leave blank to reuse the saved key, or enter a new key to rotate it · Esc returns to Base URL',
          provider:
            'Leave blank to reuse the saved key, or enter a new key to rotate it · Esc returns to provider selection',
          // The identity step only exists for create targets, so a `reuse`
          // hint never lands here; the provider text keeps the record total.
          identity:
            'Leave blank to reuse the saved key, or enter a new key to rotate it · Esc returns to provider selection',
        },
        enter: {
          baseUrl: 'Enter an API key · stored only on this machine · Esc returns to Base URL',
          provider:
            'Enter an API key · stored only on this machine · Esc returns to provider selection',
          identity:
            'Enter an API key · stored only on this machine · Esc returns to connection naming',
        },
      },
      submitAction: 'Enter to submit',
      verifyingKey: 'Verifying key…',
      modelSelectionHint: 'Search models · ↑↓ select · Space toggle · Enter save · Esc back',
      selectedModels: '{count} selected',
      selectedModelsAndSave: '{count} selected · Enter to save',
      saving: 'Saving…',
      complete: 'Complete',
      enabledModels: 'Models enabled: {count}',
      closeAction: 'Enter to close',
      thinkingUnsupported: 'This model does not support changing the thinking level.',
    },
    'zh-CN': {
      modelPickerTitle: '选择模型',
      modelSwitchCacheWarning: '⚠ 切换模型可能需要重建提示缓存；下一次请求可能更慢或成本更高。',
      modelSearchHint: '搜索模型 / 服务商 / 连接 · ↑↓ 选择 · Enter 确认 · Esc 取消',
      searchLabel: '搜索',
      noMatchingModels: '没有匹配的模型',
      selectPickerHint: '↑↓ 选择 · Enter 确认 · Esc 关闭',
      providerConfigured: '已设置',
      addAccount: '添加账号',
      thinkingLevels: {
        off: '关',
        minimal: '最小',
        low: '低',
        medium: '中',
        high: '高',
        xhigh: '超高',
        max: '最高',
      },
      defaultThinkingLevel: '默认',
      thinkingPickerTitle: '选择思考级别',
      currentMarker: '当前',
      defaultMarker: '默认',
      setupTitle: '配置模型提供商',
      baseUrlLabel: 'Base URL',
      apiKeyLabel: 'API key',
      connectionNameLabel: '名称',
      connectionSlugLabel: '标识（slug）',
      identityHint: '为该连接起名，或保留默认值自动分配 · Enter 继续 · Esc 返回',
      identitySlugInvalid: '标识需为 2–64 位小写字母、数字或连字符',
      identityNameTooLong: '名称不能超过 256 个字符',
      onboardingUnavailable: 'Onboarding 不可用：当前运行环境未提供配置入口。',
      onboardingRequestFailed: '无法连接 Runtime Host，请重试。',
      onboardingRejections: {
        provider_unsupported: '该服务商不支持 API key 配置。',
        connection_not_found: '该连接已不存在，请重新打开 /setup 后重试。',
        credential_not_configured: '需要填写 API key。',
        base_url_not_configured: '该服务商需要填写 Base URL。',
        catalog_full: '连接目录已满。',
        model_unavailable: '所选模型已不可用，请重新验证并选择。',
        slug_taken: '该标识已被占用。请更换，或清空后自动分配。',
        superseded: '该连接已发生变化，请重新打开 /setup 后重试。',
      },
      onboardingFailures: {
        auth: '服务商身份验证失败，请检查 API key 后重试。',
        timeout: '服务商验证超时，请重试。',
        provider_unavailable: '服务商当前不可用，请稍后重试。',
        network: '网络错误中断了服务商验证，请重试。',
        invalid_response: '服务商返回了无效响应，请重试。',
        unknown: '服务商验证失败，请重试。',
      },
      accountSavedRefreshFailed: '账号已保存，但模型列表暂未刷新。重启 Maka 后会重新载入。',
      listProvidersFailed: '无法读取已配置的连接。',
      noConfigurableProviders: '没有可配置的 API key 类供应商。',
      baseUrlRequired: '需要填写 Base URL',
      baseUrlInvalid: 'Base URL 不是有效的 URL',
      baseUrlProtocol: 'Base URL 必须使用 http 或 https',
      baseUrlCredentials: 'Base URL 不能包含账号密码',
      baseUrlQuery: 'Base URL 不能包含查询串或片段',
      baseUrlTooLong: 'Base URL 不能超过 2048 字节',
      selectModelBeforeSaving: '至少选择一个模型再保存',
      reuseBaseUrlHint: '留空复用已保存的 Base URL，或输入新地址替换 · Esc 返回选择服务商',
      enterBaseUrlHint: '输入中转站的 Base URL（http/https）· Esc 返回选择服务商',
      continueAction: 'Enter 继续',
      providerSearchHint: '搜索服务商，↑↓ 选择 · Enter 确认 · Esc 取消',
      noMatchingProviders: '没有匹配的服务商',
      keyHints: {
        reuse: {
          baseUrl: '留空复用已保存的 key，或输入新 key 轮换 · Esc 返回 Base URL',
          provider: '留空复用已保存的 key，或输入新 key 轮换 · Esc 返回选择服务商',
          // identity 步骤只存在于新建流程，reuse 不会落到这里；沿用 provider 文案保持记录完整。
          identity: '留空复用已保存的 key，或输入新 key 轮换 · Esc 返回选择服务商',
        },
        enter: {
          baseUrl: '输入 API key · 仅本机存储 · Esc 返回 Base URL',
          provider: '输入 API key · 仅本机存储 · Esc 返回选择服务商',
          identity: '输入 API key · 仅本机存储 · Esc 返回命名连接',
        },
      },
      submitAction: 'Enter 提交',
      verifyingKey: '正在验证 key…',
      modelSelectionHint: '搜索模型，↑↓ 选择 · Space 切换 · Enter 保存 · Esc 返回',
      selectedModels: '已选 {count}',
      selectedModelsAndSave: '已选 {count} · Enter 保存',
      saving: '正在保存…',
      complete: '完成',
      enabledModels: '已启用模型：{count}',
      closeAction: 'Enter 关闭',
      thinkingUnsupported: '当前模型不支持思考级别切换。',
    },
    'zh-TW': {
      modelPickerTitle: '選擇模型',
      modelSwitchCacheWarning: '⚠ 切換模型可能需要重建提示快取；下一次請求可能較慢或成本較高。',
      modelSearchHint: '搜尋模型 / 服務商 / 連線 · ↑↓ 選擇 · Enter 確認 · Esc 取消',
      searchLabel: '搜尋',
      noMatchingModels: '沒有符合的模型',
      selectPickerHint: '↑↓ 選擇 · Enter 確認 · Esc 關閉',
      providerConfigured: '已設定',
      addAccount: '新增帳號',
      thinkingLevels: {
        off: '關',
        minimal: '最小',
        low: '低',
        medium: '中',
        high: '高',
        xhigh: '超高',
        max: '最高',
      },
      defaultThinkingLevel: '預設',
      thinkingPickerTitle: '選擇思考級別',
      currentMarker: '目前',
      defaultMarker: '預設',
      setupTitle: '設定模型服務商',
      baseUrlLabel: 'Base URL',
      apiKeyLabel: 'API key',
      connectionNameLabel: '名稱',
      connectionSlugLabel: '識別碼（slug）',
      identityHint: '為該連線起名，或保留預設值自動分配 · Enter 繼續 · Esc 返回',
      identitySlugInvalid: '識別碼需為 2–64 位小寫字母、數字或連字號',
      identityNameTooLong: '名稱不能超過 256 個字元',
      onboardingUnavailable: 'Onboarding 無法使用：目前執行環境未提供設定入口。',
      onboardingRequestFailed: '無法連線 Runtime Host，請重試。',
      onboardingRejections: {
        provider_unsupported: '此服務商不支援 API key 設定。',
        connection_not_found: '此連線已不存在，請重新開啟 /setup 後重試。',
        credential_not_configured: '需要填寫 API key。',
        base_url_not_configured: '此服務商需要填寫 Base URL。',
        catalog_full: '連線目錄已滿。',
        model_unavailable: '所選模型已無法使用，請重新驗證並選擇。',
        slug_taken: '該識別碼已被佔用。請更換，或清空後自動分配。',
        superseded: '此連線已變更，請重新開啟 /setup 後重試。',
      },
      onboardingFailures: {
        auth: '服務商身分驗證失敗，請檢查 API key 後重試。',
        timeout: '服務商驗證逾時，請重試。',
        provider_unavailable: '服務商目前無法使用，請稍後重試。',
        network: '網路錯誤中斷了服務商驗證，請重試。',
        invalid_response: '服務商傳回無效回應，請重試。',
        unknown: '服務商驗證失敗，請重試。',
      },
      accountSavedRefreshFailed: '帳號已儲存，但模型清單尚未重新整理。重新啟動 Maka 後會重新載入。',
      listProvidersFailed: '無法讀取已設定的連線。',
      noConfigurableProviders: '沒有可設定的 API key 服務商。',
      baseUrlRequired: '需要填寫 Base URL',
      baseUrlInvalid: 'Base URL 不是有效的 URL',
      baseUrlProtocol: 'Base URL 必須使用 http 或 https',
      baseUrlCredentials: 'Base URL 不能包含帳號密碼',
      baseUrlQuery: 'Base URL 不能包含查詢字串或片段',
      baseUrlTooLong: 'Base URL 不能超過 2048 位元組',
      selectModelBeforeSaving: '至少選擇一個模型再儲存',
      reuseBaseUrlHint: '留空以重用已儲存的 Base URL，或輸入新位址替換 · Esc 返回選擇服務商',
      enterBaseUrlHint: '輸入中轉站的 Base URL（http/https）· Esc 返回選擇服務商',
      continueAction: 'Enter 繼續',
      providerSearchHint: '搜尋服務商，↑↓ 選擇 · Enter 確認 · Esc 取消',
      noMatchingProviders: '沒有符合的服務商',
      keyHints: {
        reuse: {
          baseUrl: '留空以重用已儲存的 key，或輸入新 key 輪換 · Esc 返回 Base URL',
          provider: '留空以重用已儲存的 key，或輸入新 key 輪換 · Esc 返回選擇服務商',
          // identity 步驟只存在於新建流程，reuse 不會落到這裡；沿用 provider 文案保持記錄完整。
          identity: '留空以重用已儲存的 key，或輸入新 key 輪換 · Esc 返回選擇服務商',
        },
        enter: {
          baseUrl: '輸入 API key · 僅儲存在本機 · Esc 返回 Base URL',
          provider: '輸入 API key · 僅儲存在本機 · Esc 返回選擇服務商',
          identity: '輸入 API key · 僅儲存在本機 · Esc 返回命名連線',
        },
      },
      submitAction: 'Enter 送出',
      verifyingKey: '正在驗證 key…',
      modelSelectionHint: '搜尋模型，↑↓ 選擇 · Space 切換 · Enter 儲存 · Esc 返回',
      selectedModels: '已選 {count}',
      selectedModelsAndSave: '已選 {count} · Enter 儲存',
      saving: '正在儲存…',
      complete: '完成',
      enabledModels: '已啟用模型：{count}',
      closeAction: 'Enter 關閉',
      thinkingUnsupported: '目前模型不支援思考級別切換。',
    },
  },
  'primary-guidance': {
    en: {
      welcome: {
        tagline: 'Get things done together',
        start: 'Type a message to start',
        session: 'Switch or resume a session',
        model: 'Switch models',
        setup: 'Set up a model provider',
      },
      commands: {
        compact: 'Compact session context',
        context: 'Show latest request context usage',
        copy: 'Copy the last reply (or /copy all) to the clipboard',
        exit: 'Exit Maka',
        goal: 'Show autonomous goal status',
        graph: 'Show, enable, disable, or run one Graph turn',
        help: 'Show commands and keybindings',
        mcp: 'Manage client-owned MCP servers and tool publication status',
        model: 'Select model',
        move: 'Move current session to another directory',
        new: 'Start a new session',
        permissions: 'Set session permissions',
        recap: 'One-sentence recap of the session so far',
        rename: 'Rename current session',
        resume: 'Resume latest interrupted run at a safe boundary',
        rewind: 'Rewind to an earlier turn',
        session: 'Resume session',
        setup: 'Set up a model provider (API key)',
        side: 'Open a temporary side conversation',
        skill: 'Invoke a skill (or type /skill:<name> inline)',
        swarm: 'Show, enable, disable, or run one Swarm turn',
        thinking: 'Set thinking level',
        transcript: 'Browse the full transcript inside Maka',
      },
      help: {
        commandsHeading: 'Commands',
        userCommand: '  !<command> — run one shell command visible only to you',
        keybindingsHeading: 'Keybindings',
        keybindings: [
          '  Ctrl+O — expand or collapse all tool output',
          '  Ctrl+T — expand or collapse all thinking in view',
          '  Scroll the transcript with your terminal or trackpad',
          '  Enter (during a turn) — steer: inject a message into the running turn',
          '  Alt+Enter (during a turn) — queue a message for the next turn',
          '  Alt+↑ — take queued messages back into the editor to re-edit',
          '  Esc Esc (during a turn) — interrupt the turn',
          '  Esc Esc (when idle) — rewind to an earlier turn',
          '  Ctrl+C — stop the turn, clear input, or press twice to exit',
          '  Ctrl+D — exit when input is empty',
        ],
      },
    },
    'zh-CN': {
      welcome: {
        tagline: '陪你把事做完',
        start: '输入消息开始对话',
        session: '切换或恢复会话',
        model: '切换模型',
        setup: '配置模型提供商',
      },
      commands: {
        compact: '压缩会话上下文',
        context: '查看最近一次请求的上下文用量',
        copy: '复制最后一条回复（或 /copy all）到剪贴板',
        exit: '退出 Maka',
        goal: '查看自主目标状态',
        graph: '查看、启用、停用 Graph 模式，或执行一次 Graph 任务',
        help: '查看命令和快捷键',
        mcp: '管理客户端 MCP 服务器和工具发布状态',
        model: '选择模型',
        move: '将当前会话移到其他目录',
        new: '新建会话',
        permissions: '设置会话权限',
        recap: '用一句话总结当前会话',
        rename: '重命名当前会话',
        resume: '从安全边界恢复最近一次中断的执行',
        rewind: '回退到较早的对话轮次',
        session: '切换或恢复会话',
        setup: '配置模型提供商（API Key）',
        side: '打开临时 Side Conversation',
        skill: '调用 Skill（也可直接输入 /skill:<name>）',
        swarm: '查看、启用、停用 Swarm 模式，或执行一次 Swarm 任务',
        thinking: '设置思考级别',
        transcript: '在 Maka 内浏览完整对话记录',
      },
      help: {
        commandsHeading: '命令',
        userCommand: '  !<command> — 执行一次仅用户可见的 shell 命令',
        keybindingsHeading: '快捷键',
        keybindings: [
          '  Ctrl+O — 展开或折叠所有工具输出',
          '  Ctrl+T — 展开或折叠视图中的所有思考块',
          '  使用终端或触控板滚动对话记录',
          '  Enter（任务运行中）— 将消息注入当前任务',
          '  Alt+Enter（任务运行中）— 将消息排入下一轮',
          '  Alt+↑ — 将已排队消息取回编辑器重新编辑',
          '  Esc Esc（任务运行中）— 中断当前任务',
          '  Esc Esc（空闲时）— 回退到较早的轮次',
          '  Ctrl+C — 停止任务、清空输入，或连续按两次退出',
          '  Ctrl+D — 输入为空时退出',
        ],
      },
    },
    'zh-TW': {
      welcome: {
        tagline: '陪你把事做完',
        start: '輸入訊息開始對話',
        session: '切換或恢復會話',
        model: '切換模型',
        setup: '設定模型服務商',
      },
      commands: {
        compact: '壓縮會話上下文',
        context: '檢視最近一次請求的上下文用量',
        copy: '複製最後一則回覆（或 /copy all）到剪貼簿',
        exit: '退出 Maka',
        goal: '檢視自主目標狀態',
        graph: '檢視、啟用、停用 Graph 模式，或執行一次 Graph 任務',
        help: '檢視命令和快捷鍵',
        mcp: '管理用戶端 MCP 伺服器與工具發佈狀態',
        model: '選擇模型',
        move: '將目前會話移到其他目錄',
        new: '建立會話',
        permissions: '設定會話權限',
        recap: '用一句話總結目前會話',
        rename: '重新命名目前會話',
        resume: '從安全邊界恢復最近一次中斷的執行',
        rewind: '回退到較早的對話輪次',
        session: '切換或恢復會話',
        setup: '設定模型服務商（API Key）',
        side: '開啟臨時 Side Conversation',
        skill: '呼叫 Skill（也可直接輸入 /skill:<name>）',
        swarm: '檢視、啟用、停用 Swarm 模式，或執行一次 Swarm 任務',
        thinking: '設定思考級別',
        transcript: '在 Maka 內瀏覽完整對話記錄',
      },
      help: {
        commandsHeading: '命令',
        userCommand: '  !<command> — 執行一次僅使用者可見的 shell 命令',
        keybindingsHeading: '快捷鍵',
        keybindings: [
          '  Ctrl+O — 展開或摺疊所有工具輸出',
          '  Ctrl+T — 展開或摺疊檢視中的所有思考區塊',
          '  使用終端機或觸控板捲動對話記錄',
          '  Enter（任務執行中）— 將訊息注入目前任務',
          '  Alt+Enter（任務執行中）— 將訊息排入下一輪',
          '  Alt+↑ — 將已排隊訊息取回編輯器重新編輯',
          '  Esc Esc（任務執行中）— 中斷目前任務',
          '  Esc Esc（空閒時）— 回退到較早的輪次',
          '  Ctrl+C — 停止任務、清空輸入，或連續按兩次退出',
          '  Ctrl+D — 輸入為空時退出',
        ],
      },
    },
  },
  rewind: {
    en: {
      pickerTitle: 'Rewind',
      pending: 'Rewinding to before this turn…',
      doneRefilled:
        'Rewound to before this turn (branched into a new task; the original task is kept). The turn’s prompt was refilled into the input box — edit it and send again.',
      doneKeptDraft:
        'Rewound to before this turn (branched into a new task; the original task is kept). The input box already had unsent content and was left untouched; the turn’s prompt was saved to input history — press ↑ to recall it.',
      noTargets: 'No turns to rewind to.',
      busy: 'Cannot rewind: another action is in progress — wait for it to finish, or interrupt (Esc) and retry.',
      pickerHint:
        'Return to before the selected turn (discards it and later turns; the prompt refills the input box) · enter select / esc cancel',
    },
    'zh-CN': {
      pickerTitle: '回退',
      pending: '正在回退到该轮之前…',
      doneRefilled:
        '已回退到该轮之前（分支为新任务，原任务保留），该轮 prompt 已回填输入框，可修改后重新发送。',
      doneKeptDraft:
        '已回退到该轮之前（分支为新任务，原任务保留）。输入框已有未发送内容，未覆盖；该轮 prompt 已存入输入历史，可按 ↑ 找回。',
      noTargets: '没有可回退的轮次。',
      busy: '无法回退：当前有正在进行的操作 — 请等待其完成，或中断（Esc）后重试。',
      pickerHint: '回到选定轮次之前（丢弃该轮及之后，prompt 回填输入框） · enter 选择 / esc 取消',
    },
    'zh-TW': {
      pickerTitle: '回退',
      pending: '正在回退到該輪之前…',
      doneRefilled:
        '已回退到該輪之前（分支為新任務，原任務保留），該輪 prompt 已回填輸入框，可修改後重新傳送。',
      doneKeptDraft:
        '已回退到該輪之前（分支為新任務，原任務保留）。輸入框已有未傳送內容，未覆蓋；該輪 prompt 已存入輸入歷史，可按 ↑ 找回。',
      noTargets: '沒有可回退的輪次。',
      busy: '無法回退：目前有正在進行的操作 — 請等待完成，或中斷（Esc）後重試。',
      pickerHint: '回到選定輪次之前（捨棄該輪及之後，prompt 回填輸入框） · enter 選擇 / esc 取消',
    },
  },
  skills: {
    en: {
      pickerTitle: 'Invoke Skill',
      usage: 'Usage: /skill, or type /skill:<name> inline in a message',
      noneAvailable: 'No skills are available to invoke right now.',
      loaded: 'Skills loaded: {names}',
      loadFailed: 'Could not load skills {failures}; {outcome}',
      outcomeNoRequest: 'no model request was made.',
      outcomeMarkersNotSent: 'the failed invocation markers were not sent to the model.',
      failedItem: '/skill:{request} ({reason})',
      tooManyRequestsItem: 'more than the {limit}-request limit ({reason})',
      listSeparator: ', ',
      failureReasons: {
        invalid_name: 'invalid name',
        not_found: 'not found',
        disabled: 'disabled',
        host_incompatible: 'the current host is missing a tool it depends on',
        resolution_failed: 'resolution failed',
        too_many_requests: 'too many requests',
      },
    },
    'zh-CN': {
      pickerTitle: '调用技能',
      usage: 'Usage: /skill，或直接在消息中输入 /skill:<name>',
      noneAvailable: '当前没有可调用的技能。',
      loaded: '已加载技能：{names}',
      loadFailed: '未能加载技能 {failures}；{outcome}',
      outcomeNoRequest: '未发起模型请求。',
      outcomeMarkersNotSent: '失败的调用标记未发送给模型。',
      failedItem: '/skill:{request}（{reason}）',
      tooManyRequestsItem: '请求超过 {limit} 个上限（{reason}）',
      listSeparator: '、',
      failureReasons: {
        invalid_name: '名称无效',
        not_found: '未找到',
        disabled: '已禁用',
        host_incompatible: '当前主机缺少其依赖的工具',
        resolution_failed: '解析失败',
        too_many_requests: '调用请求过多',
      },
    },
    'zh-TW': {
      pickerTitle: '呼叫技能',
      usage: 'Usage: /skill，或直接在訊息中輸入 /skill:<name>',
      noneAvailable: '目前沒有可呼叫的技能。',
      loaded: '已載入技能：{names}',
      loadFailed: '無法載入技能 {failures}；{outcome}',
      outcomeNoRequest: '未發起模型請求。',
      outcomeMarkersNotSent: '失敗的呼叫標記未傳送給模型。',
      failedItem: '/skill:{request}（{reason}）',
      tooManyRequestsItem: '請求超過 {limit} 個上限（{reason}）',
      listSeparator: '、',
      failureReasons: {
        invalid_name: '名稱無效',
        not_found: '找不到',
        disabled: '已停用',
        host_incompatible: '目前主機缺少其相依工具',
        resolution_failed: '解析失敗',
        too_many_requests: '呼叫請求過多',
      },
    },
  },
  'connection-identity': {
    en: {
      withRecovery: '{notice} {recovery}',
      emptyChoiceRecovery:
        'If /model has no choices, add or enable a connection first (run /setup for API-key connections).',
      confirmAccount:
        'This task comes from an older version and needs a one-time account confirmation. Run /model and choose an existing account and model.',
      accountDeleted:
        'The original account was deleted. Run /model and choose a new account and model to continue.',
      identityMismatch:
        'The saved account identity no longer matches its connection. Run /model and choose an account and model again.',
      accountDisabled:
        'The original account is disabled. Enable it, or run /model and choose a new account and model.',
    },
    'zh-CN': {
      withRecovery: '{notice}{recovery}',
      emptyChoiceRecovery:
        '如果 /model 没有可选项，请先添加或启用连接（API Key 连接可运行 /setup）。',
      confirmAccount: '此任务来自旧版本，需要确认一次账号。运行 /model 选择现有账号和模型。',
      accountDeleted: '原账号已删除；运行 /model 选择新账号和模型后继续。',
      identityMismatch: '任务保存的账号身份与当前连接不一致；运行 /model 重新选择账号和模型。',
      accountDisabled: '原账号已停用；请启用该账号，或运行 /model 选择新账号和模型。',
    },
    'zh-TW': {
      withRecovery: '{notice}{recovery}',
      emptyChoiceRecovery:
        '如果 /model 沒有可選項，請先新增或啟用連線（API Key 連線可執行 /setup）。',
      confirmAccount: '此任務來自舊版本，需要確認一次帳號。執行 /model 選擇現有帳號和模型。',
      accountDeleted: '原帳號已刪除；執行 /model 選擇新帳號和模型後繼續。',
      identityMismatch: '任務儲存的帳號身分與目前連線不一致；執行 /model 重新選擇帳號和模型。',
      accountDisabled: '原帳號已停用；請啟用該帳號，或執行 /model 選擇新帳號和模型。',
    },
  },
  'session-actions': {
    en: {
      foreignScanFailed: 'Could not read external conversations: {detail}',
      newSessionFailed:
        'Could not start a new session: a local command could not be stopped. Press Ctrl+C to stop it, then try again.',
    },
    'zh-CN': {
      foreignScanFailed: '读取外部对话失败：{detail}',
      newSessionFailed: '无法开始新会话：无法停止本地命令。请按 Ctrl+C 停止命令后重试。',
    },
    'zh-TW': {
      foreignScanFailed: '讀取外部對話失敗：{detail}',
      newSessionFailed: '無法開始新工作階段，請稍後重試。',
    },
  },
  'pending-queue': {
    en: {
      steeringLabel: 'Steering:',
      queuedLabel: 'Queued:',
      requeueHint: 'Alt+↑ take queued messages back to re-edit',
    },
    'zh-CN': {
      steeringLabel: '注入：',
      queuedLabel: '已排队：',
      requeueHint: 'Alt+↑ 取回队列以重新编辑',
    },
    'zh-TW': {
      steeringLabel: '調整方向：',
      queuedLabel: '已排入佇列：',
      requeueHint: 'Alt+↑ 取回佇列訊息重新編輯',
    },
  },
  'session-status': {
    en: {
      running: 'running',
      waitingForUser: 'waiting for you',
      permissionRequired: 'needs permission',
      connectionRequired: 'needs connection',
      signInRequired: 'needs sign-in',
      stopped: 'stopped',
    },
    'zh-CN': {
      running: '进行中',
      waitingForUser: '等你确认',
      permissionRequired: '需要权限',
      connectionRequired: '需要连接',
      signInRequired: '需要重新登录',
      stopped: '已中止',
    },
    'zh-TW': {
      running: '進行中',
      waitingForUser: '等你確認',
      permissionRequired: '需要權限',
      connectionRequired: '需要連線',
      signInRequired: '需要重新登入',
      stopped: '已中止',
    },
  },
} as const;
